"""Coverage for ai-attribution-blocker hook.

Source rule: `~/.claude/CLAUDE.md` "No AI attribution" and
`~/.claude/rules/git-workflow.md`.
"""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

import pytest

HOOK = "ai-attribution-blocker"


@pytest.mark.parametrize(
    "line",
    [
        "Co-authored-by: Claude <noreply@anthropic.com>",
        "Co-authored-by: someone Anthropic AI",
        "co-authored-by: GPT bot",
        "Co-Authored-By: Copilot",
        "Co-authored-by: Cursor IDE",
    ],
)
def test_blocks_coauthored_by_ai(tool_use, assert_blocks, line):
    # Arrange
    payload = tool_use(
        "Bash",
        {"command": f"git commit -m 'fix: handle null\n\n{line}'"},
    )

    # Act / Assert
    assert_blocks(HOOK, payload, "AI attribution detected")


@pytest.mark.parametrize(
    "phrase",
    [
        "Generated by Claude",
        "Generated with AI",
        "Generated by GPT",
        "Generated with Copilot",
        "Generated by an AI",
        "generated by a AI",
    ],
)
def test_blocks_generated_by_ai(tool_use, assert_blocks, phrase):
    # Arrange
    payload = tool_use(
        "Write",
        {
            "file_path": "/repo/src/notes.txt",
            "content": f"# Project notes\n\n{phrase}.\n",
        },
    )

    # Act / Assert
    assert_blocks(HOOK, payload, "AI attribution detected")


def test_blocks_ai_assisted(tool_use, assert_blocks):
    # Arrange
    payload = tool_use(
        "Write",
        {
            "file_path": "/repo/README.txt",
            "content": "This module is AI-assisted.\n",
        },
    )

    # Act / Assert
    assert_blocks(HOOK, payload, "AI attribution detected")


def test_blocks_ai_assisted_with_space(tool_use, assert_blocks):
    # Arrange
    payload = tool_use(
        "Write",
        {
            "file_path": "/repo/README.txt",
            "content": "This module is AI assisted.\n",
        },
    )

    # Act / Assert
    assert_blocks(HOOK, payload, "AI attribution detected")


@pytest.mark.parametrize(
    "phrase",
    [
        "Written by Claude",
        "Written by AI",
        "Written by GPT",
    ],
)
def test_blocks_written_by(tool_use, assert_blocks, phrase):
    # Arrange
    payload = tool_use(
        "Edit",
        {
            "file_path": "/repo/src/util.txt",
            "old_string": "old",
            "new_string": f"{phrase}\n",
        },
    )

    # Act / Assert
    assert_blocks(HOOK, payload, "AI attribution detected")


def test_blocks_authored_by_claude(tool_use, assert_blocks):
    # Arrange
    payload = tool_use(
        "Bash",
        {"command": "gh pr create --body 'Authored-by-Claude\nSee diff.'"},
    )

    # Act / Assert
    assert_blocks(HOOK, payload, "AI attribution detected")


@pytest.mark.parametrize(
    "tag",
    ["[Claude]", "[Claude Code]", "[claude]", "[CLAUDE CODE]"],
)
def test_blocks_claude_tag(tool_use, assert_blocks, tag):
    # Arrange
    payload = tool_use(
        "Write",
        {
            "file_path": "/repo/CHANGELOG.txt",
            "content": f"## v1\n{tag} added a feature.\n",
        },
    )

    # Act / Assert
    assert_blocks(HOOK, payload, "AI attribution detected")


def test_blocks_multiedit_with_attribution_in_one_edit(tool_use, assert_blocks):
    # Arrange
    payload = tool_use(
        "MultiEdit",
        {
            "file_path": "/repo/src/x.ts",
            "edits": [
                {"old_string": "a", "new_string": "// clean section a"},
                {
                    "old_string": "b",
                    "new_string": "// Co-authored-by: Claude in section b",
                },
            ],
        },
    )

    # Act / Assert
    assert_blocks(HOOK, payload, "AI attribution detected")


def test_blocks_bash_heredoc(tool_use, assert_blocks):
    # Arrange
    payload = tool_use(
        "Bash",
        {
            "command": (
                "gh api repos/owner/repo/pulls --field body=\"$(cat <<'EOF'\n"
                "Fix the bug\n\n"
                "Co-authored-by: Claude <bot@example.com>\n"
                "EOF\n"
                ')"'
            )
        },
    )

    # Act / Assert
    assert_blocks(HOOK, payload, "AI attribution detected")


def test_allows_clean_commit(tool_use, assert_allows):
    # Arrange
    payload = tool_use(
        "Bash",
        {"command": "git commit -m 'fix: handle null user id'"},
    )

    # Act / Assert
    assert_allows(HOOK, payload)


def test_allows_clean_write(tool_use, assert_allows):
    # Arrange
    payload = tool_use(
        "Write",
        {
            "file_path": "/repo/src/app.ts",
            "content": "export const greet = () => 'hello';\n",
        },
    )

    # Act / Assert
    assert_allows(HOOK, payload)


def test_allows_human_coauthored_by(tool_use, assert_allows):
    # Arrange
    payload = tool_use(
        "Bash",
        {
            "command": (
                "git commit -m 'feat: ship\n\n"
                "Co-authored-by: Jane Doe <jane@example.com>'"
            )
        },
    )

    # Act / Assert
    assert_allows(HOOK, payload)


@pytest.mark.parametrize(
    "doc_path",
    [
        "/Users/gufranco/.claude/CLAUDE.md",
        "/Users/gufranco/.claude/rules/example.md",
        "/Users/gufranco/.claude/standards/example.md",
        "/Users/gufranco/.claude/checklists/checklist.md",
        "/Users/gufranco/.claude/hooks/some-hook.py",
        "/Users/gufranco/.claude/skills/example.md",
    ],
)
def test_skipped_paths_allow_attribution_examples(tool_use, assert_allows, doc_path):
    # Arrange
    payload = tool_use(
        "Write",
        {
            "file_path": doc_path,
            "content": "Examples of patterns: Generated by Claude, AI-assisted.\n",
        },
    )

    # Act / Assert
    assert_allows(HOOK, payload)


def test_skipped_path_for_edit(tool_use, assert_allows):
    # Arrange
    payload = tool_use(
        "Edit",
        {
            "file_path": "/Users/gufranco/.claude/rules/example.md",
            "old_string": "old",
            "new_string": "Generated by Claude is forbidden.",
        },
    )

    # Act / Assert
    assert_allows(HOOK, payload)


def test_skipped_path_for_multiedit(tool_use, assert_allows):
    # Arrange
    payload = tool_use(
        "MultiEdit",
        {
            "file_path": "/Users/gufranco/.claude/standards/example.md",
            "edits": [
                {"old_string": "x", "new_string": "Generated by AI sample text"},
            ],
        },
    )

    # Act / Assert
    assert_allows(HOOK, payload)


def test_skipped_tests_directory(tool_use, assert_allows):
    # Arrange
    payload = tool_use(
        "Write",
        {
            "file_path": "/repo/tests/example.py",
            "content": "fixture = 'Generated by Claude'\n",
        },
    )

    # Act / Assert
    assert_allows(HOOK, payload)


def test_disable_env_bypasses(tool_use, assert_allows):
    # Arrange
    payload = tool_use(
        "Bash",
        {"command": "git commit -m 'fix\n\nCo-authored-by: Claude'"},
    )

    # Act / Assert
    assert_allows(HOOK, payload, env={"AI_ATTRIBUTION_DISABLE": "1"})


def test_disable_env_other_value_does_not_bypass(tool_use, assert_blocks):
    # Arrange
    payload = tool_use(
        "Bash",
        {"command": "git commit -m 'fix\n\nCo-authored-by: Claude'"},
    )

    # Act / Assert
    assert_blocks(
        HOOK,
        payload,
        "AI attribution detected",
        env={"AI_ATTRIBUTION_DISABLE": "0"},
    )


def test_unknown_tool_is_ignored(tool_use, assert_allows):
    # Arrange
    payload = tool_use("Read", {"file_path": "/repo/src/x.ts"})

    # Act / Assert
    assert_allows(HOOK, payload)


def test_write_non_string_content_is_safe(tool_use, assert_allows):
    # Arrange
    payload = tool_use(
        "Write",
        {"file_path": "/repo/src/x.ts", "content": 42},
    )

    # Act / Assert
    assert_allows(HOOK, payload)


def test_edit_non_string_new_string_is_safe(tool_use, assert_allows):
    # Arrange
    payload = tool_use(
        "Edit",
        {
            "file_path": "/repo/src/x.ts",
            "old_string": "a",
            "new_string": 999,
        },
    )

    # Act / Assert
    assert_allows(HOOK, payload)


def test_multiedit_non_dict_items_are_safe(tool_use, assert_allows):
    # Arrange
    payload = tool_use(
        "MultiEdit",
        {
            "file_path": "/repo/src/x.ts",
            "edits": ["not a dict", None, 42],
        },
    )

    # Act / Assert
    assert_allows(HOOK, payload)


def test_multiedit_non_string_new_string_is_safe(tool_use, assert_allows):
    # Arrange
    payload = tool_use(
        "MultiEdit",
        {
            "file_path": "/repo/src/x.ts",
            "edits": [{"old_string": "a", "new_string": 12345}],
        },
    )

    # Act / Assert
    assert_allows(HOOK, payload)


def test_bash_non_string_command_is_safe(tool_use, assert_allows):
    # Arrange
    payload = tool_use("Bash", {"command": 42})

    # Act / Assert
    assert_allows(HOOK, payload)


def test_empty_file_path_with_clean_content(tool_use, assert_allows):
    # Arrange
    payload = tool_use(
        "Write",
        {"file_path": "", "content": "Clean content.\n"},
    )

    # Act / Assert
    assert_allows(HOOK, payload)


def test_long_attribution_snippet_truncates(tool_use, assert_blocks):
    # Arrange
    long_prefix = "x" * 200
    long_suffix = "y" * 200
    payload = tool_use(
        "Write",
        {
            "file_path": "/repo/src/x.txt",
            "content": f"{long_prefix}\nGenerated by Claude\n{long_suffix}",
        },
    )

    # Act / Assert
    assert_blocks(HOOK, payload, "AI attribution detected")


def test_invalid_json_stdin_does_not_crash():
    # Arrange
    hook_path = (
        Path(__file__).resolve().parents[3] / "hooks" / "ai-attribution-blocker.py"
    )
    env = dict(os.environ)
    env["CLAUDE_HOOK_AUDIT_DISABLE"] = "1"
    for k in ("COVERAGE_PROCESS_START", "PYTHONPATH"):
        if k in os.environ:
            env[k] = os.environ[k]

    # Act
    proc = subprocess.run(
        [sys.executable, str(hook_path)],
        input="not valid json",
        capture_output=True,
        text=True,
        env=env,
        timeout=6.0,
        check=False,
    )

    # Assert
    assert proc.returncode == 0
