#!/usr/bin/env python3
"""Compile the session memory directory from the second brain vault.

The vault is the source of truth. The memory directory is a generated artifact
with a size budget, so it can finally do the three operations a hand-maintained
memory store never does: update, compress, and forget.

Forgetting here means demotion, never deletion. A demoted entry leaves the
memory directory and stays in the vault, so nothing is lost by evicting it.

Safety, because the vault carries no version control:

  - a file without ``generated_from`` is never touched, and is reported as
    unmanaged, since a human wrote it
  - the plan is printed before anything is written, and applying is opt-in
  - the current directory is copied into the backup tree before an apply

Usage:

    python3 .github/scripts/memory-compile.py [--path DIR] [--memory DIR]
        [--budget CHARS] [--apply] [--json]

Rule source: ``rules/knowledge-notes.md``.
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import sys
from dataclasses import dataclass
from datetime import date
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT / "hooks"))

from _lib import knowledge_notes as kn  # noqa: E402

DEFAULT_MEMORY = Path.home() / ".claude" / "projects" / "-Users-gufranco" / "memory"
DEFAULT_BACKUPS = REPO_ROOT / "backups"
DEFAULT_BUDGET = 40_000
INDEX_NAME = "MEMORY.md"
INDEX_MARKER = "This file is generated by the memory compile."
DEMOTED_DIR = "_demoted"
GENERATED_KEY = "generated_from"
SCOPES = ("user", "feedback", "project", "reference")
SCOPE_RANK = {scope: index for index, scope in enumerate(SCOPES)}
SLUG_UNSAFE = re.compile(r"[^a-z0-9]+")
TRUTHY = ("true", "yes", "1")


@dataclass(frozen=True)
class Entry:
    slug: str
    scope: str
    source: str
    description: str
    body: str
    updated: str

    @property
    def filename(self) -> str:
        return f"{self.slug}.md"

    @property
    def weight(self) -> int:
        return len(self.body) + len(self.description)


def slugify(stem: str) -> str:
    return SLUG_UNSAFE.sub("-", stem.lower()).strip("-") or "note"


def collect(root: Path) -> list[Entry]:
    """Return every vault note that opted into memory, ordered by scope then name."""
    entries: list[Entry] = []
    for rel, text in kn.iter_notes(root):
        fields = kn.parse_frontmatter(text)
        if not fields:
            continue
        if fields.get("memory", "").strip().lower() not in TRUTHY:
            continue
        scope = fields.get("memory-scope", "").strip()
        if scope not in SCOPE_RANK:
            continue
        body = kn.body_after_frontmatter(text).strip()
        entries.append(
            Entry(
                slug=slugify(rel.stem),
                scope=scope,
                source=rel.as_posix(),
                description=fields.get("description", f"Compiled from {rel.stem}"),
                body=body,
                updated=fields.get("date", date.today().isoformat()),
            )
        )
    return sorted(entries, key=lambda entry: (SCOPE_RANK[entry.scope], entry.slug))


def render(entry: Entry) -> str:
    """Render one memory file, stamped with the vault note it came from."""
    return (
        "---\n"
        f"name: {entry.slug}\n"
        f"description: {entry.description}\n"
        f"type: {entry.scope}\n"
        f"{GENERATED_KEY}: {entry.source}\n"
        f"updated: {entry.updated}\n"
        "---\n\n"
        f"{entry.body}\n"
    )


def render_index(entries: list[Entry]) -> str:
    """Render the index the harness loads at session start."""
    lines = [
        "# Memory",
        "",
        f"{INDEX_MARKER} Do not edit it by hand:",
        "the next compile overwrites it. Edit the vault note named under each entry.",
        "",
    ]
    for scope in SCOPES:
        in_scope = [entry for entry in entries if entry.scope == scope]
        if not in_scope:
            continue
        lines.append(f"## {scope.capitalize()}")
        lines.append("")
        for entry in in_scope:
            lines.append(f"- [{entry.slug}]({entry.filename}) - {entry.description}")
        lines.append("")
    if not entries:
        lines.append("No vault note has opted into memory yet.")
        lines.append("")
    return "\n".join(lines)


def managed_files(memory: Path) -> dict[str, str]:
    """Map each memory file to its provenance, empty when a human wrote it.

    The index carries no frontmatter, so it declares itself managed with a
    marker sentence instead. A hand-maintained index is left alone, exactly
    like a hand-written entry.
    """
    found: dict[str, str] = {}
    for path in sorted(memory.glob("*.md")):
        try:
            text = path.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):  # pragma: no cover
            continue
        if path.name == INDEX_NAME:
            found[path.name] = INDEX_NAME if INDEX_MARKER in text else ""
            continue
        fields = kn.parse_frontmatter(text) or {}
        found[path.name] = fields.get(GENERATED_KEY, "")
    return found


def within_budget(entries: list[Entry], budget: int) -> tuple[list[Entry], list[str]]:
    kept: list[Entry] = []
    evicted: list[str] = []
    spent = 0
    for entry in entries:
        if spent + entry.weight > budget:
            evicted.append(entry.filename)
            continue
        spent += entry.weight
        kept.append(entry)
    return kept, evicted


def plan(root: Path, memory: Path, budget: int = DEFAULT_BUDGET) -> dict:
    """Return the exact set of writes, moves, and refusals the apply would make."""
    entries, over_budget = within_budget(collect(root), budget)
    rendered = {entry.filename: render(entry) for entry in entries}
    rendered[INDEX_NAME] = render_index(entries)

    existing = managed_files(memory)
    unmanaged = sorted(name for name, source in existing.items() if not source)
    generated = {name for name, source in existing.items() if source}

    create: list[str] = []
    update: list[str] = []
    for name, text in rendered.items():
        target = memory / name
        if name in unmanaged:
            continue
        if not target.exists():
            create.append(name)
        elif target.read_text(encoding="utf-8") != text:
            update.append(name)

    demote = sorted(generated - set(rendered) - {INDEX_NAME})

    return {
        "create": create,
        "update": update,
        "demote": demote,
        "unmanaged": unmanaged,
        "over_budget": over_budget,
        "rendered": rendered,
        "spent": sum(entry.weight for entry in entries),
        "budget": budget,
    }


def apply(
    prepared: dict, memory: Path, backup_dir: Path | None = DEFAULT_BACKUPS
) -> None:
    """Write the planned changes, after copying the current directory aside."""
    touched = prepared["create"] + prepared["update"] + prepared["demote"]
    if backup_dir is not None and touched:
        stamp = date.today().isoformat()
        destination = backup_dir / f"memory-{stamp}"
        if destination.exists():
            shutil.rmtree(destination)
        shutil.copytree(memory, destination)

    for name in prepared["create"] + prepared["update"]:
        if name in prepared["unmanaged"]:
            continue
        (memory / name).write_text(prepared["rendered"][name], encoding="utf-8")

    if prepared["demote"]:
        graveyard = memory / DEMOTED_DIR
        graveyard.mkdir(parents=True, exist_ok=True)
        for name in prepared["demote"]:
            shutil.move(str(memory / name), str(graveyard / name))


def render_report(prepared: dict, applied: bool) -> str:
    lines: list[str] = []
    for label in ("create", "update", "demote", "unmanaged", "over_budget"):
        names = prepared[label]
        if names:
            lines.append(f"{label}: {', '.join(names)}")
    if not lines:
        return "nothing to do: the memory directory already matches the vault"
    lines.append(f"budget: {prepared['spent']} of {prepared['budget']} characters")
    lines.append("applied" if applied else "dry run, pass --apply to write")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Compile memory from the vault.")
    parser.add_argument("--path", default=None)
    parser.add_argument("--memory", default=str(DEFAULT_MEMORY))
    parser.add_argument("--budget", type=int, default=DEFAULT_BUDGET)
    parser.add_argument("--apply", action="store_true")
    parser.add_argument("--json", action="store_true")
    args = parser.parse_args(argv)

    root = kn.vault_root(args.path)
    if root is None:
        target = args.path or "SECOND_BRAIN_VAULT"
        print(f"memory-compile: {target} is not a directory", file=sys.stderr)
        return 2

    memory = Path(args.memory)
    if not memory.is_dir():
        print(
            f"memory-compile: memory directory {memory} does not exist", file=sys.stderr
        )
        return 2

    prepared = plan(root, memory, budget=args.budget)
    if args.apply:
        apply(prepared, memory)

    if args.json:
        printable = {key: value for key, value in prepared.items() if key != "rendered"}
        printable["applied"] = args.apply
        print(json.dumps(printable, indent=2))
    else:
        print(render_report(prepared, args.apply))
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
