#!/usr/bin/env python3
"""
ai-attribution-blocker.py

PreToolUse hook that blocks AI attribution lines in commits, PRs, and code.
Rule source: ~/.claude/CLAUDE.md "No AI attribution" and ~/.claude/rules/git-workflow.md.

Scans:
  - Write.content
  - Edit.new_string
  - MultiEdit.edits[].new_string
  - Bash.command  (catches `git commit -m`, `gh pr create --body`, heredocs)

Bypass:
  AI_ATTRIBUTION_DISABLE=1
"""

from __future__ import annotations

import json
import os
import re
import sys

sys.path.insert(0, os.path.expanduser("~/.claude/hooks"))
try:
    from _lib.audit_log import record as _audit  # type: ignore
except Exception:  # pragma: no cover

    def _audit(**_fields):  # type: ignore
        return None


PATTERNS = [
    re.compile(
        r"Co-authored-by:\s*.*\b(Claude|Anthropic|AI|GPT|Copilot|Cursor)\b",
        re.IGNORECASE,
    ),
    re.compile(
        r"\bGenerated\s+(?:by|with)\s+(?:Claude|AI|GPT|Copilot|an?\s+AI)\b",
        re.IGNORECASE,
    ),
    re.compile(r"\bAI[- ]assisted\b", re.IGNORECASE),
    re.compile(r"\bWritten\s+by\s+(?:Claude|AI|GPT)\b", re.IGNORECASE),
    re.compile(r"Authored[- ]by[- ]Claude", re.IGNORECASE),
    re.compile(r"\[Claude(?:\s+Code)?\]", re.IGNORECASE),
]

from _lib.bypass import is_bypassed  # noqa: E402


def _snippet(text: str, idx: int) -> str:
    start = max(0, idx - 40)
    end = min(len(text), idx + 60)
    return text[start:end].replace("\n", " | ")


def find_violations(text: str) -> list[tuple[str, str]]:
    out: list[tuple[str, str]] = []
    for pat in PATTERNS:
        m = pat.search(text)
        if m:
            out.append((m.group(0), _snippet(text, m.start())))
    return out


SKIPPED_DOC_SEGMENTS = (
    "/.claude/CLAUDE.md",
    "/.claude/rules/",
    "/.claude/standards/",
    "/.claude/checklists/",
    "/.claude/hooks/",
    "/.claude/skills/",
)

# Test fixtures legitimately contain attribution strings to exercise the hook.
# Skip pytest fixture paths so the hook does not block its own coverage tests.
SKIPPED_TEST_SEGMENTS = (
    "/tests/",
    "/test/",
    "/__tests__/",
    ".test.",
    ".spec.",
)


def is_skipped_path(path: str) -> bool:
    if not path:
        return False
    if any(seg in path for seg in SKIPPED_DOC_SEGMENTS):
        return True
    p = path.lower()
    if any(seg in p for seg in SKIPPED_TEST_SEGMENTS):
        return True
    return False


def collect_texts(tool: str, tool_input: dict) -> list[tuple[str, str]]:
    out: list[tuple[str, str]] = []
    fp = tool_input.get("file_path", "") or ""
    if tool in ("Write", "Edit", "MultiEdit") and is_skipped_path(fp):
        return out
    if tool == "Write":
        c = tool_input.get("content", "")
        if isinstance(c, str):
            out.append(("content", c))
    elif tool == "Edit":
        c = tool_input.get("new_string", "")
        if isinstance(c, str):
            out.append(("new_string", c))
    elif tool == "MultiEdit":
        for i, edit in enumerate(tool_input.get("edits", []) or []):
            if isinstance(edit, dict):
                c = edit.get("new_string", "")
                if isinstance(c, str):
                    out.append((f"edits[{i}].new_string", c))
    elif tool == "Bash":
        c = tool_input.get("command", "")
        if isinstance(c, str):
            out.append(("command", c))
    return out


import sys as _sys  # noqa: E402
import os as _os  # noqa: E402

_sys.path.insert(0, _os.path.expanduser("~/.claude/hooks"))
try:
    from _lib.hook_profile import should_run  # noqa: E402
except ImportError:

    def should_run(_id: str) -> bool:
        return True


def main() -> int:
    if not should_run("ai-attribution-blocker"):
        _sys.exit(0)
    if os.environ.get("AI_ATTRIBUTION_DISABLE") == "1":
        _audit(
            hook="ai-attribution-blocker",
            decision="bypass",
            bypass_env="AI_ATTRIBUTION_DISABLE",
        )
        return 0
    if is_bypassed("ai-attribution-blocker"):
        return 0

    try:
        payload = json.load(sys.stdin)
    except Exception:
        return 0

    tool = payload.get("tool_name", "")
    tool_input = payload.get("tool_input", {}) or {}

    texts = collect_texts(tool, tool_input)
    if not texts:
        return 0

    findings: list[str] = []
    for field, text in texts:
        for match, snippet in find_violations(text):
            findings.append(f"  - {match!r} in {field}: ...{snippet}...")

    if not findings:
        return 0

    print(
        "Blocked: AI attribution detected. "
        "Rule: ~/.claude/CLAUDE.md (No AI attribution) and ~/.claude/rules/git-workflow.md.\n"
        + "\n".join(findings)
        + "\n\nFix: remove the attribution line. Never add Co-authored-by or 'Generated by AI' "
        "to commits, PR descriptions, or code.\n"
        "Bypass (rare): set AI_ATTRIBUTION_DISABLE=1 in the environment.",
        file=sys.stderr,
    )
    _audit(
        hook="ai-attribution-blocker",
        decision="block",
        tool=tool,
        reason="AI attribution detected",
        command_excerpt=" | ".join(findings)[:240] if findings else None,
    )
    return 2


if __name__ == "__main__":
    sys.exit(main())
