#!/usr/bin/env python3
"""
ai-process-leak-blocker.py

PreToolUse hook that blocks AI-process language from leaking into
artifacts other engineers will read: git commit messages, PR
descriptions, release notes, code comments. Complements
ai-attribution-blocker.py, which only catches explicit attribution
strings like "Generated by Claude".

Detects the more subtle leak pattern: language that exposes the
workflow shape (multi-phase plan, spec folders, canvas-region mapping,
LLM-style hyperbole). A human engineer would never write these phrases
in a commit message because they describe the process of producing the
change, not the change itself.

Scans:
  - Write.content
  - Edit.new_string
  - MultiEdit.edits[].new_string
  - Bash.command  (catches `git commit -m`, `gh pr create --body`,
                   heredocs feeding either)

Bypass:
  AI_PROCESS_LEAK_DISABLE=1
"""

from __future__ import annotations

import json
import os
import re
import sys

sys.path.insert(0, os.path.expanduser("~/.claude/hooks"))
try:
    from _lib.audit_log import record as _audit  # type: ignore
except Exception:  # pragma: no cover

    def _audit(**_fields):  # type: ignore
        return None


# Patterns that almost always indicate AI-process leakage. Each one
# names a phrase a human engineer would not write in a commit message
# or PR description, because it refers to the artifact the AI produced
# rather than the code under review.
PATTERNS: list[tuple[re.Pattern[str], str]] = [
    # "Phase 1", "phase 12", "Phase 0 of the regnant plan"
    (
        re.compile(r"\bPhase\s+\d+\b", re.IGNORECASE),
        "Phase-N language belongs in a planning document, not a commit",
    ),
    # "of the plan", "per the plan", "the regnant plan"
    (
        re.compile(r"\b(?:of|per|in|the)\s+the\s+(?:regnant\s+)?plan\b", re.IGNORECASE),
        "References to 'the plan' expose the AI workflow",
    ),
    # "Refs: specs/..." trailer (path inside the repo's planning folder)
    (
        re.compile(r"\bRefs?:\s*specs?/", re.IGNORECASE),
        "Refs: specs/ trailer references planning artifacts",
    ),
    # ".../plan.md" anywhere in a message
    (
        re.compile(r"/plan\.md\b", re.IGNORECASE),
        "plan.md is a planning artifact; do not reference it in commits",
    ),
    # "spec folder", "spec folders"
    (
        re.compile(r"\bspec\s+folders?\b", re.IGNORECASE),
        "Spec folder is an AI workflow artifact, not human commit content",
    ),
    # "Maps to canvas region X" or "canvas region"
    (
        re.compile(r"\b(?:maps?\s+to\s+)?canvas\s+region\b", re.IGNORECASE),
        "Canvas-region language exposes the design-artifact mapping",
    ),
    # "state-of-the-art" / "state of the art" hyperbole
    (
        re.compile(r"\bstate[-\s]of[-\s]the[-\s]art\b", re.IGNORECASE),
        "State-of-the-art is an LLM hyperbole tell",
    ),
    # "100% faithful", "fully faithful", "absolutely faithful"
    (
        re.compile(
            r"\b(?:100%|fully|absolutely|perfectly)\s+faithful\b", re.IGNORECASE
        ),
        "Faithfulness language is AI-process hyperbole",
    ),
    # "ADR-NNNN" referenced casually in a commit subject or body
    # (ADRs themselves are fine; mentioning by number in commit text is suspicious)
    (
        re.compile(r"\bADR-\d{3,4}\b"),
        "ADR-NNNN references in commits read as AI cross-linking",
    ),
    # "comes online in", "lands in phase N"
    (
        re.compile(
            r"\b(?:lands?|comes?|arrives?)\s+(?:in|online)\s+(?:phase\s+\d+|a\s+later\s+phase)\b",
            re.IGNORECASE,
        ),
        "Phase-relative scheduling exposes the AI plan",
    ),
    # "per the plan", "as the plan describes", "following the plan"
    (
        re.compile(
            r"\b(?:following|as|per)\s+(?:the\s+plan|the\s+spec)\b", re.IGNORECASE
        ),
        "Referencing 'the plan/spec' as authority is AI workflow language",
    ),
    # "I ran the suite", "I ran the tests", "I ran jest", "I ran the full suite"
    (
        re.compile(
            r"\bI\s+ran\s+(?:the\s+)?(?:suite|tests?|jest|full\s+suite|spec|specs|coverage)\b",
            re.IGNORECASE,
        ),
        "Narrating the verification loop. State the result, not the steps",
    ),
    # "observed the actual status", "observed the behavior", "observed the response"
    (
        re.compile(
            r"\bobserved\s+(?:the\s+)?(?:actual\s+)?(?:status|behaviou?r|return|response|result|output)\b",
            re.IGNORECASE,
        ),
        "Empirical-observation narration. Just state the result",
    ),
    # "for each X case I ran", "for each X I tried", "for each X I observed"
    (
        re.compile(
            r"\bfor\s+each\s+\S+(?:[ -]\S+)?\s+(?:case|test|assertion),?\s+I\s+(?:ran|tried|observed|asserted|checked)\b",
            re.IGNORECASE,
        ),
        "Meta-iteration over test cases reads as AI workflow self-talk",
    ),
    # "with the asserts pinned to match", "pinned to match the actual"
    (
        re.compile(
            r"\b(?:with\s+the\s+asserts?\s+pinned\s+to\s+match|pinned\s+to\s+match\s+the\s+actual)\b",
            re.IGNORECASE,
        ),
        "Frames verification as the deliverable. The deliverable is the code",
    ),
    # "All 21 tests still pass", "All 102 integration tests pass", "All N tests pass"
    (
        re.compile(
            r"\bAll\s+\d+\s+(?:\w+\s+){0,3}tests?\s+(?:still\s+)?pass(?:es|ed)?\b",
            re.IGNORECASE,
        ),
        "Verification-summary trailer. CI conveys this; the comment should not",
    ),
]

from _lib.bypass import is_bypassed  # noqa: E402



def _snippet(text: str, idx: int) -> str:
    start = max(0, idx - 40)
    end = min(len(text), idx + 80)
    return text[start:end].replace("\n", " | ")


def find_violations(text: str) -> list[tuple[str, str, str]]:
    out: list[tuple[str, str, str]] = []
    for pat, reason in PATTERNS:
        m = pat.search(text)
        if m:
            out.append((m.group(0), reason, _snippet(text, m.start())))
    return out


# Skip the user's own planning and rule files: those legitimately
# contain phase-N language and spec-folder paths.
SKIPPED_PATH_SEGMENTS = (
    "/.claude/",
    "/specs/",
    "/docs/adr/",
    "/docs/plan",
    "/docs/runbook",
)


def is_skipped_path(path: str) -> bool:
    if not path:
        return False
    return any(seg in path for seg in SKIPPED_PATH_SEGMENTS)


# Inside Bash payloads, the leak only matters when the command is one
# that publishes text to other humans: git commit, gh pr create/edit,
# glab mr create, hub pr/issue, and PR-review-comment endpoints reached
# through `gh api`. Other commands (cat, grep, tofu apply with a
# -message flag) are not in scope.
GIT_AND_PR_PATTERNS = (
    re.compile(r"\bgit\s+commit\b"),
    re.compile(r"\bgit\s+tag\b.*-m\b"),
    re.compile(r"\bgh\s+pr\s+(create|edit|comment)\b"),
    re.compile(r"\bgh\s+release\s+(create|edit)\b"),
    re.compile(r"\bgh\s+issue\s+(create|edit|comment)\b"),
    # PR review comment replies and edits via `gh api`. Covers paths
    # like `repos/<owner>/<repo>/pulls/<n>/comments/<id>/replies` (POST)
    # and `repos/<owner>/<repo>/pulls/comments/<id>` (PATCH). The check
    # is loose on purpose: any `gh api` call that names a comments
    # endpoint is treated as in-scope and its `--input` payload is read.
    re.compile(r"\bgh\s+api\b.*\b(pulls|issues)\b.*\bcomments\b"),
    re.compile(r"\bglab\s+mr\s+(create|update|note)\b"),
    re.compile(r"\bglab\s+release\s+create\b"),
)


def bash_command_in_scope(command: str) -> bool:
    return any(pat.search(command) for pat in GIT_AND_PR_PATTERNS)


# Flags that point at a file whose contents are published by the command.
# Example: `gh pr create --body-file /tmp/pr.md` writes the file's contents
# into the PR description. The command string itself does not contain the
# leak; the file does. Read those files at hook time so leaks in their
# bodies are caught the same way an inline -m argument would be.
BODY_FILE_FLAGS = (
    "--body-file",
    "--description-file",
    "--notes-file",
    "--notes-from-tag",
    "--input",
    "-F",
)

# Parse `--body-file PATH` (space-separated) and `--body-file=PATH` forms.
# Tokenize on whitespace, then look for each flag and the next token. The
# regex also handles single-quoted and double-quoted paths. `--input` is
# the `gh api` payload flag; when present, the file is JSON whose `body`
# field carries the comment text the rule must scan.
_FLAG_VALUE_TOKEN = re.compile(
    r"""(?P<flag>--body-file|--description-file|--notes-file|--notes-from-tag|--input|-F)
        (?:\s*=\s*|\s+)
        (?P<value>"[^"]+"|'[^']+'|\S+)""",
    re.VERBOSE,
)


def extract_body_file_paths(command: str) -> list[str]:
    """Return every path referenced by a body-file-like flag in the command."""
    out: list[str] = []
    for m in _FLAG_VALUE_TOKEN.finditer(command):
        raw = m.group("value")
        if raw.startswith(('"', "'")):
            raw = raw[1:-1]
        if raw:
            out.append(raw)
    return out


def read_body_file(path: str) -> str | None:
    """Read a body-file referenced by a CLI flag. Return None on any error.

    The hook must not crash on a missing or unreadable file: the underlying
    command will fail anyway, and the hook's job is to scan content, not
    enforce file existence.
    """
    try:
        from pathlib import Path

        p = Path(path).expanduser()
        if not p.is_file():
            return None
        return p.read_text(encoding="utf-8", errors="replace")
    except Exception:
        return None


def collect_texts(tool: str, tool_input: dict) -> list[tuple[str, str]]:
    out: list[tuple[str, str]] = []
    fp = tool_input.get("file_path", "") or ""
    if tool in ("Write", "Edit", "MultiEdit") and is_skipped_path(fp):
        return out
    if tool == "Write":
        c = tool_input.get("content", "")
        if isinstance(c, str):
            out.append(("content", c))
    elif tool == "Edit":
        c = tool_input.get("new_string", "")
        if isinstance(c, str):
            out.append(("new_string", c))
    elif tool == "MultiEdit":
        for i, edit in enumerate(tool_input.get("edits", []) or []):
            if isinstance(edit, dict):
                c = edit.get("new_string", "")
                if isinstance(c, str):
                    out.append((f"edits[{i}].new_string", c))
    elif tool == "Bash":
        c = tool_input.get("command", "")
        if isinstance(c, str) and bash_command_in_scope(c):
            out.append(("command", c))
            # Also scan the contents of any --body-file / --description-file
            # / --notes-file the command points at. Without this the hook
            # only inspects the command line and misses leaks that the body
            # file carries into a PR/MR/release description.
            for path in extract_body_file_paths(c):
                body = read_body_file(path)
                if body is not None:
                    out.append((f"body-file:{path}", body))
    return out


import sys as _sys  # noqa: E402
import os as _os  # noqa: E402

_sys.path.insert(0, _os.path.expanduser("~/.claude/hooks"))
try:
    from _lib.hook_profile import should_run  # noqa: E402
except ImportError:

    def should_run(_id: str) -> bool:
        return True


def main() -> int:
    if not should_run("ai-process-leak-blocker"):
        _sys.exit(0)
    if os.environ.get("AI_PROCESS_LEAK_DISABLE") == "1":
        _audit(
            hook="ai-process-leak-blocker",
            decision="bypass",
            bypass_env="AI_PROCESS_LEAK_DISABLE",
        )
        return 0
    if is_bypassed("ai-process-leak-blocker"):
        return 0

    try:
        payload = json.load(sys.stdin)
    except Exception:
        return 0

    tool = payload.get("tool_name", "")
    tool_input = payload.get("tool_input", {}) or {}

    texts = collect_texts(tool, tool_input)
    if not texts:
        return 0

    findings: list[str] = []
    for field, text in texts:
        for match, reason, snippet in find_violations(text):
            findings.append(
                f"  - {match!r} ({reason})\n    in {field}: ...{snippet}..."
            )

    if not findings:
        return 0

    print(
        "Blocked: AI process language detected in artifact that other engineers will read.\n"
        "Rule: ~/.claude/CLAUDE.md and feedback memory 'no AI process leak in commits/PRs/code'.\n\n"
        + "\n".join(findings)
        + "\n\nFix: rewrite as if a human engineer wrote it. State what changed and why,\n"
        "not which phase of which plan produced the change. Strip references to spec\n"
        "folders, plan.md, canvas regions, ADR numbers, and hyperbole like 'state-of-the-art'.\n\n"
        "Bypass (rare; only when editing the planning artifacts themselves):\n"
        "  export AI_PROCESS_LEAK_DISABLE=1",
        file=sys.stderr,
    )
    _audit(
        hook="ai-process-leak-blocker",
        decision="block",
        tool=tool,
        reason="AI process language detected",
        command_excerpt=" | ".join(f[:120] for f in findings)[:240]
        if findings
        else None,
    )
    return 2


if __name__ == "__main__":
    sys.exit(main())
