"""Coverage for ai-disclosure-checks hook.

Source rule: `~/.claude/rules/ai-compliance-defaults.md`.
"""

from __future__ import annotations


HOOK = "ai-disclosure-checks"


def test_blocks_aiResponse_without_disclosure(tool_use, assert_blocks):
    # Arrange
    payload = tool_use(
        "Write",
        {
            "file_path": "/repo/src/Answer.tsx",
            "content": (
                "function Answer({ aiResponse }) {\n"
                "  return <article>{aiResponse}</article>;\n"
                "}\n"
            ),
        },
    )

    # Act / Assert
    assert_blocks(HOOK, payload, "AIC001")


def test_blocks_llmOutput_without_disclosure(tool_use, assert_blocks):
    # Arrange
    payload = tool_use(
        "Write",
        {
            "file_path": "/repo/src/X.tsx",
            "content": (
                "function X({ llmOutput }) {\n  return <div>{llmOutput}</div>;\n}\n"
            ),
        },
    )

    # Act / Assert
    assert_blocks(HOOK, payload, "AIC001")


def test_blocks_modelOutput_without_disclosure(tool_use, assert_blocks):
    # Arrange
    payload = tool_use(
        "Write",
        {
            "file_path": "/repo/src/X.tsx",
            "content": (
                "function X({ data }) {\n  return <p>{data.modelOutput}</p>;\n}\n"
            ),
        },
    )

    # Act / Assert
    assert_blocks(HOOK, payload, "AIC001")


def test_allows_aiResponse_with_disclosure(tool_use, assert_allows):
    # Arrange
    payload = tool_use(
        "Write",
        {
            "file_path": "/repo/src/Answer.tsx",
            "content": (
                "function Answer({ aiResponse }) {\n"
                "  return (\n"
                "    <article>\n"
                "      <AiDisclosure>AI generated</AiDisclosure>\n"
                "      <p>{aiResponse}</p>\n"
                "    </article>\n"
                "  );\n"
                "}\n"
            ),
        },
    )

    # Act / Assert
    assert_allows(HOOK, payload)


def test_allows_aiResponse_with_powered_by_AI_label(tool_use, assert_allows):
    # Arrange
    payload = tool_use(
        "Write",
        {
            "file_path": "/repo/src/Answer.tsx",
            "content": (
                "function Answer({ aiResponse }) {\n"
                "  return (\n"
                "    <article aria-label='AI generated response'>\n"
                "      <p>{aiResponse}</p>\n"
                "      <footer>This response was generated by AI.</footer>\n"
                "    </article>\n"
                "  );\n"
                "}\n"
            ),
        },
    )

    # Act / Assert
    assert_allows(HOOK, payload)


def test_blocks_chatbot_without_AI_label(tool_use, assert_blocks):
    # Arrange
    payload = tool_use(
        "Write",
        {
            "file_path": "/repo/src/Support.tsx",
            "content": (
                "function Support() {\n"
                "  return (\n"
                "    <Chatbot>\n"
                "      <Message>How can I help?</Message>\n"
                "    </Chatbot>\n"
                "  );\n"
                "}\n"
            ),
        },
    )

    # Act / Assert
    assert_blocks(HOOK, payload, "AIC002")


def test_allows_chatbot_with_AI_label(tool_use, assert_allows):
    # Arrange
    payload = tool_use(
        "Write",
        {
            "file_path": "/repo/src/Support.tsx",
            "content": (
                "function Support() {\n"
                "  return (\n"
                "    <div>\n"
                "      <h2>Support powered by AI</h2>\n"
                "      <Chatbot>\n"
                "        <Message>Hello, I am the support assistant powered by AI.</Message>\n"
                "      </Chatbot>\n"
                "    </div>\n"
                "  );\n"
                "}\n"
            ),
        },
    )

    # Act / Assert
    assert_allows(HOOK, payload)


def test_allows_non_ai_variables(tool_use, assert_allows):
    # Arrange
    payload = tool_use(
        "Write",
        {
            "file_path": "/repo/src/X.tsx",
            "content": (
                "function X({ userName }) {\n  return <p>Hello {userName}</p>;\n}\n"
            ),
        },
    )

    # Act / Assert
    assert_allows(HOOK, payload)


def test_skips_test_files(tool_use, assert_allows):
    # Arrange
    payload = tool_use(
        "Write",
        {
            "file_path": "/repo/src/Answer.test.tsx",
            "content": (
                "function Answer({ aiResponse }) {\n"
                "  return <article>{aiResponse}</article>;\n"
                "}\n"
            ),
        },
    )

    # Act / Assert
    assert_allows(HOOK, payload)


def test_skips_non_jsx_files(tool_use, assert_allows):
    # Arrange
    payload = tool_use(
        "Write",
        {
            "file_path": "/repo/src/util.ts",
            "content": 'const x = "<Chatbot>foo</Chatbot>";',
        },
    )

    # Act / Assert
    assert_allows(HOOK, payload)


def test_bypass_env_disables(tool_use, assert_allows):
    # Arrange
    payload = tool_use(
        "Write",
        {
            "file_path": "/repo/src/Answer.tsx",
            "content": (
                "function Answer({ aiResponse }) {\n"
                "  return <article>{aiResponse}</article>;\n"
                "}\n"
            ),
        },
    )

    # Act / Assert
    assert_allows(HOOK, payload, env={"AI_DISCLOSURE_DISABLE": "1"})


def test_works_on_edit_payload(tool_use, assert_blocks):
    # Arrange
    payload = tool_use(
        "Edit",
        {
            "file_path": "/repo/src/Answer.tsx",
            "old_string": "old",
            "new_string": "function Answer({ aiResponse }) { return <article>{aiResponse}</article>; }",
        },
    )

    # Act / Assert
    assert_blocks(HOOK, payload, "AIC001")


def test_works_on_multiedit_payload(tool_use, assert_blocks):
    # Arrange
    payload = tool_use(
        "MultiEdit",
        {
            "file_path": "/repo/src/Answer.tsx",
            "edits": [
                {
                    "old_string": "a",
                    "new_string": "function Answer({ aiResponse }) { return <article>{aiResponse}</article>; }",
                },
            ],
        },
    )

    # Act / Assert
    assert_blocks(HOOK, payload, "AIC001")


def test_ignores_bash_tool(tool_use, assert_allows):
    # Arrange
    payload = tool_use(
        "Bash",
        {"command": "echo aiResponse"},
    )

    # Act / Assert
    assert_allows(HOOK, payload)


def test_skips_dist_folder(tool_use, assert_allows):
    # Arrange
    payload = tool_use(
        "Write",
        {
            "file_path": "/repo/dist/Answer.tsx",
            "content": "function Answer({ aiResponse }) { return <article>{aiResponse}</article>; }",
        },
    )

    # Act / Assert
    assert_allows(HOOK, payload)


def test_empty_content_allows(tool_use, assert_allows):
    # Arrange
    payload = tool_use(
        "Write",
        {
            "file_path": "/repo/src/X.tsx",
            "content": "",
        },
    )

    # Act / Assert
    assert_allows(HOOK, payload)
